branches:
  only:
  - main

language: node_js
node_js:
  - 14

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
## Assuming the .travis.yml file is in the project directory, and there is a separate sub-directory for each service
## Use either `docker-compose` or individual `docker build` commands
## Build
  - docker build -t udagram-frontend ./udagram-frontend

## Tagging
  - docker tag udagram-frontend phucnh4798/udagram-frontend:v1

