branches:
  only:
  - main

language: node_js
node_js:
  - 14

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
## Assuming the .travis.yml file is in the project directory, and there is a separate sub-directory for each service
## Use either `docker-compose` or individual `docker build` commands
## Build
  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker build -t udagram-api-user ./udagram-api-user
  - docker build -t udagram-frontend ./udagram-frontend
  - docker build -t reverseproxy ./udagram-reverseproxy

## Tagging
  - docker tag udagram-api-feed phucnh4798/udagram-api-feed:latest
  - docker tag udagram-api-user phucnh4798/udagram-api-user:latest
  - docker tag udagram-frontend phucnh4798/udagram-frontend:latest
  - docker tag reverseproxy phucnh4798/reverseproxy:latest


after_success:
## Push
## Assuming DOCKER_PASSWORD and DOCKER_USERNAME are set in the Travis repository settings
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push phucnh4798/udagram-api-feed
  - docker push phucnh4798/udagram-api-user
  - docker push phucnh4798/udagram-frontend
  - docker push phucnh4798/reverseproxy
