version: 2.1

executors:
  docker-executor:
    docker:
      - image: docker:20.10.16 # Docker version
    working_directory: /app
    resource_class: medium
    environment:
      DOCKER_HOST: tcp://docker:2375
      DOCKER_TLS_CERTDIR: ""

jobs:
  build:
    executor: docker-executor
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.16
      - run:
          name: Build Docker Image
          command: |
              docker build -t udagram-api-feed ./udagram-api-feed
              docker build -t udagram-api-user ./udagram-api-user
              docker build -t udagram-front ./udagram-front
              docker build -t reverseproxy ./reverseproxy
      - run:
          name: Tag Docker Image
          command: |
              docker tag udagram-api-feed sudkul/udagram-api-feed:v1
              docker tag udagram-api-user sudkul/udagram-api-user:v1
              docker tag udagram-front sudkul/udagram-front:v1
              docker tag reverseproxy sudkul/reverseproxy:v1
      - run:
          name: Push Docker Image
          command: |
        echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        docker push sudkul/udagram-api-feed:v1
        docker push sudkul/udagram-api-user:v1
        docker push sudkul/udagram-front:v1
        docker push sudkul/reverseproxy:v1

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build